version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.docker/rabbitmq/rabbitmq_schema.json:/etc/rabbitmq/rabbitmq_schema.json
    ports:
      - 5672:5672
      - 8080:15672